### ISSUE TITLE
/etc/sysctl.conf文件出错

### ISSUE THREAD

**Issue by yuhuan21** [glzjin/shadowsocks#13]
编辑/etc/sysctl.conf以后,执行sysctl -p,报错
![qq 20161110152613](https://cloud.githubusercontent.com/assets/10203925/20167995/35a0e7ee-a75a-11e6-8253-ced90576c5f2.png)

**Comment by a86913179** [comment]
openvz很多参数不支持修改

**Comment by glzjin** [comment]
@a86913179 没事

**Comment by a86913179** [comment]
@glzjin 嗯，因为有些参数还是生效了

**Comment by yuhuan21** [comment]
@glzjin @a86913179 那就是说,还是可以支持openvz的主机对吧?

**Comment by a86913179** [comment]
@yuhuan21 是的，没有出现error的那2条生效了
