### ISSUE TITLE
客户端把udp转发打开就打不开网页了

### ISSUE THREAD

**Issue by jeffreys125** [glzjin/shadowsocks#15]
手机客户端把udp转发打开后能收到qq，微信的消息。但是就打不开网页。。这个不支持udp转发吗？
我用的是多用户版的。。

**Comment by glzjin** [comment]
@jeffreys125 什么类型的端口？

**Comment by jeffreys125** [comment]
@glzjin 53,137,138那种的。

**Comment by jeffreys125** [comment]
@glzjin 其他端口正常可以udp转发
