### ISSUE TITLE
Bug Report：提供的gui-config.json加密方式与数据库不匹配

### ISSUE THREAD

**Issue by brucx** [glzjin/shadowsocks#26]
version: 1ee344220afce9c8b2d031830d23bc6d8849c39c
description: `.config.php`中设置的`$System_Config['reg_method']='rc4-md5';`但是下载的`gui-config.json`文件中的加密方式为`aes-256-cfb`

**Comment by glzjin** [comment]
@brucx 与这个没有关系。
