### ISSUE TITLE
限速无法使用

### ISSUE THREAD

**Issue by Fribyter** [glzjin/shadowsocks#33]
在用户和节点里都设置了限速，可是不起作用，看视频瞬间把带宽给跑满了
3Mbps小水管，给节点每个用户限制了1Mbps，在线用户只有一个，youtube测速3340kbps

**Comment by glzjin** [comment]
@Fribyter 你面板上这个截图和这个节点的SSR链接发出来

**Comment by Fribyter** [comment]
@glzjin 感谢回复 
![qq 20161231145225](https://cloud.githubusercontent.com/assets/23735503/21576406/e3afd2c4-cf68-11e6-955a-f26ce550a36e.png)

**Comment by glzjin** [comment]
@Fribyter ssr 链接呢

**Comment by Fribyter** [comment]
http://www.fribyter.site/ @glzjin 是站点吗

**Comment by glzjin** [comment]
@Fribyter 连接信息，SSR 链接。

**Comment by Fribyter** [comment]
服务器地址: www.fribyter.site
服务器端口: 1992
服务器密码: 818283
协议插件 (protocol): auth_aes128_md5
混淆插件 (obfs): tls1.2_ticket_auth
加密方式: chacha20

用这个吧 @glzjin

**Comment by glzjin** [comment]
@Fribyter 你确定这个帐号有限速的吧？把这个帐号在面板上的用户名密码也给我

**Comment by glzjin** [comment]
@Fribyter 对了 你后端配置发一下

**Comment by Fribyter** [comment]
@glzjin b406434710@126.com 1234567890

**Comment by Fribyter** [comment]
@glzjin 后端哪个配置config.php么

**Comment by glzjin** [comment]
@Fribyter user-apiconfg.py

**Comment by Fribyter** [comment]
`
# Config
NODE_ID = 3


#hour,set 0 to disable
SPEEDTEST = 6
CLOUDSAFE = 1
ANTISSATTACK = 0
AUTOEXEC = 0
MULTI_THREAD = 0

MU_SUFFIX = 'zhaoj.in'
MU_REGEX = '%5m%id.%suffix'

SERVER_PUB_ADDR = '127.0.0.1' # mujson_mgr need this to generate ssr link
API_INTERFACE = 'glzjinmod' #mudbjson, sspanelv2, sspanelv3, sspanelv3ssr, muapiv2(not support)

#mudb
MUDB_FILE = 'mudb.json'

# Mysql
MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = 3306
MYSQL_USER = 'sspanel'
MYSQL_PASS = 'root'
MYSQL_DB = 'sspanel'
MYSQL_UPDATE_TIME = 60

MYSQL_SSL_ENABLE = 0
MYSQL_SSL_CA = ''
MYSQL_SSL_CERT = ''
MYSQL_SSL_KEY = ''

# API
API_HOST = '127.0.0.1'
API_PORT = 80
API_PATH = '/mu/v2/'
API_TOKEN = 'abcdef'
API_UPDATE_TIME = 60

# Manager (ignore this)
MANAGE_PASS = 'ss233333333'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333
`

@glzjin

**Comment by glzjin** [comment]
@Fribyter multi thread 改成1之后限速才会生效

**Comment by Fribyter** [comment]
@glzjin 非常感谢，文档里没看到这个，我试试去

**Comment by Fribyter** [comment]
@glzjin 这应该只是一个标识符吧，还是限速的数值？

**Comment by glzjin** [comment]
@Fribyter 安装文档里有 1为开 0为关

**Comment by Fribyter** [comment]
@glzjin 哥，我试了下，刚multi thread 调成1了重启了下服务器，上了下youtube还是跑到3000多kbps了

**Comment by glzjin** [comment]
@Fribyter 把SSR链接发出来

**Comment by glzjin** [comment]
@Fribyter 算了 直接发个测试账户来 调好限速

**Comment by Fribyter** [comment]
服务器地址: 118.193.234.24
服务器端口: 1992
服务器密码: 818283 
协议插件 (protocol): auth_aes128_md5
混淆插件 (obfs): tls1.2_ticket_auth
加密方式: chacha20

@glzjin

**Comment by glzjin** [comment]
@Fribyter 我请你发面板的测试帐号

**Comment by Fribyter** [comment]
@glzjin ryu7898@hanmail.net ryu950205

**Comment by glzjin** [comment]
@Fribyter 行 不用了 我刚才测试确实是限速生效了 请自己用 beta.speedtest.net 测试

**Comment by glzjin** [comment]
@Fribyter Android 手机上 开全局模式 然后 speedtest

**Comment by Fribyter** [comment]
@glzjin 这个限速仅仅针对 TCP协议吗？

**Comment by Fribyter** [comment]
针对UDP的限速有办法么

**Comment by glzjin** [comment]
@Fribyter 没有

**Comment by Fribyter** [comment]
@glzjin 那就蛋疼了，youtube上可以走udp

**Comment by glzjin** [comment]
@Fribyter 你把UDP封了不就好了

**Comment by Fribyter** [comment]
游戏加速来说，udp转发很重要

**Comment by glzjin** [comment]
@Fribyter 那你自己想办法咯 反正我没空去弄

**Comment by Fribyter** [comment]
@glzjin 嗯 谢谢了
