### ISSUE TITLE
后端链接端口问题

### ISSUE THREAD

**Issue by zackvv** [glzjin/shadowsocks#9]
群里看了那么久没看到有人问这个问题，大概是都会吧！
我找了半天没找到答案麻烦科普下。
后端这对接端口冲突问题
2016-11-01 16:08:54 INFO     server_pool.py:164 starting server at 0.0.0.0:52008
2016-11-01 16:08:54 WARNING  server_pool.py:176 IPV4 [Errno 98] Address already in use 
只要是在前端加端口他就会报冲突，并不是某一个。
这样报错，用netstat -nap找到pid 用kill -9杀掉，phyhon他会换个进程继续执行。后端用了supervisord运行
reboot过也没用。请问这种问题是需要怎么样解决呢？ 大神有时间解答下，谢谢！

**Comment by glzjin** [comment]
@zackvv 你运行了多个后端实例

**Comment by zackvv** [comment]
这种应该怎么解决呢？问过用kill杀死，可是没用，我基础不是很好，麻烦可以具体说下么

**Comment by glzjin** [comment]
@zackvv 你检查你哪里尝试运行了多个后端了 自己多上网搜搜 这里并没有义务教你这些

**Comment by zackvv** [comment]
好吧谢谢

**Comment by zackvv** [comment]
好吧谢谢

**Comment by zackvv** [comment]
好吧谢谢
